"""add incidents

Revision ID: 4f6782f5ce44
Revises: e3cffa904812
Create Date: 2026-08-26 15:05:30.550723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import database


# revision identifiers, used by Alembic.
revision: str = '4f6782f5ce44'
down_revision: Union[str, None] = 'e3cffa904812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('machine', sa.String(length=120), nullable=False),
    sa.Column('asset_tag', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kb_id', sa.String(length=36), nullable=True),
    sa.Column('sensor_analysis_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('risk_json', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=120), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('ai_error', sa.Text(), nullable=True),
    sa.Column('recommendation_action', sa.Text(), nullable=True),
    sa.Column('recommendation_risk_level', sa.String(length=20), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approval_request_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', database.UTCDateTime(), nullable=False),
    sa.Column('updated_at', database.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_analysis_id'], ['sensor_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_owner_id'))

    op.drop_table('incidents')
    # ### end Alembic commands ###
