"""add inspection_images

Revision ID: 789b154435c5
Revises: 4f6782f5ce44
Create Date: 2026-08-26 16:11:30.047310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import database


# revision identifiers, used by Alembic.
revision: str = '789b154435c5'
down_revision: Union[str, None] = '4f6782f5ce44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=120), nullable=True),
    sa.Column('created_at', database.UTCDateTime(), nullable=False),
    sa.Column('updated_at', database.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_images_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_images_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_images_owner_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_images_incident_id'))

    op.drop_table('inspection_images')
    # ### end Alembic commands ###
