"""add sensor_analyses

Revision ID: e3cffa904812
Revises: 838a7d4139b1
Create Date: 2026-08-26 14:22:58.130242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import database


# revision identifiers, used by Alembic.
revision: str = 'e3cffa904812'
down_revision: Union[str, None] = '838a7d4139b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('encoding', sa.String(length=20), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('timestamp_column', sa.String(length=100), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=120), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('ai_explanation_error', sa.Text(), nullable=True),
    sa.Column('created_at', database.UTCDateTime(), nullable=False),
    sa.Column('updated_at', database.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensor_analyses_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_analyses_owner_id'))

    op.drop_table('sensor_analyses')
    # ### end Alembic commands ###
